### ISSUE TITLE
git log --pretty=format:%%h is abbreviated hash

### ISSUE THREAD

**Issue by johanfange** [ShenXiaolong1976/sourceIndex_forGit#1]
Looks like an awesome project!

One thing, I think it would be better to store the full hash of the commit in the PDB.

By using:

    git log --pretty=format:%%h

...you will get the abbreviated hash. Instead for the full hash you could use (capital H):

    git log --pretty=format:%%H

**Comment by shenxiaolong-code** [comment]
fixed: use full hash.
thanks to johanfange
