### ISSUE TITLE
Tool takes a very long time

### ISSUE THREAD

**Issue by DavidLevy-Leddartech** [ShenXiaolong1976/sourceIndex_forGit#2]
Hello,
i'm trying to use your tool to source index a very basic project.

So, i update the environment variable `set localGitRepo=C:\Git\test`

and then I run the actual command

`C:\Users\user101\Desktop\sourceIndex_forGit-master\gitIndex.cmd "C:\Git\test" "C:\Git\test\x64\Release"`

But then, the first line is `rem call gitIndex.cmd "" ""`

followed by several errors:

>find: '/i': No such file or directory
>find: '/c/$Recycle.Bin/S-1-5-18': Permission denied
f>ind: '/c/$Recycle.Bin/S-1-5-21-1035048477-112209276-915462001-1000': Permission denied                                 find: >'/c/$Recycle.Bin/S-1-5-21-1035048477-112209276-915462001-1001': Permission denied
>find: '/c/$Recycle.Bin/S-1-5-21-1035048477-112209276-915462001-500': Permission denied
>find: '/c/$Recycle.Bin/S-1-5-21-1457439002-884234708-2329215277-500': Permission denied
>find: '/c/$Recycle.Bin/S-1-5-21-2500424245-2055191009-4082716798-4653': Permission denied
>find: '/c/PerfLogs/Admin': Permission denied

I have also tried to set `LocalProjectSrcPath` and `pdbFilePathOrPdbFolderPath`, but I still have the same errors

**Comment by shenxiaolong-code** [comment]
Hi ,
all those variables are used by your debugger. 
the source indexing procedure needn't those variables. 
for the source index procedure, you only need to confirm userLocalPathConfig.bat configuration is correct with your current environment.

the line : rem call gitIndex.cmd "%LocalProjectSrcPath%" "%pdbFilePathOrPdbFolderPath%"
it is only a usage example comments.


you can refer to the usage example in test folder.
or in your visual studio project : solution explorer -> right click -> Properties -> Build Events -> Post-Build Event :
Command Line : call C:\myScript\gitIndex.cmd "$(projectDir)" "$(targetdir)$(targetname).pdb"

as a basic test project, you can package them and send it to me (xlshen2002@gamil.com) , I will check it.

**Comment by shenxiaolong-code** [comment]
if it works, but it takes a very long time, it is caused by the git version mechanism.
but this implement is a huge source index procedure -- it is slow when source indexing, but much faster when the debugger is using them.

if you like a fast light source index procedure, you can try  : 
https://github.com/ShenXiaolong1976/sourceIndexLight_forGit
it is faster when source indexing, but much slower when the debugger is using them because you have to sync all repo files with a special git version which embed into the PDB file.

**Comment by shenxiaolong-code** [comment]
index slower , debug faster   -- use :  https://github.com/ShenXiaolong1976/sourceIndex_forGit
index faster  , debug slower  -- use :  https://github.com/ShenXiaolong1976/sourceIndexLight_forGit
